import { uiAssets } from '@assets/index';
import { t } from '@shared/i18n';
import type { TradeRecord } from './types';

export const SHARED_CANDLE_DATA: TradeRecord['candleData'] = [
  { open: 1.082, high: 1.086, low: 1.079, close: 1.084 },
  { open: 1.084, high: 1.087, low: 1.081, close: 1.082 },
  { open: 1.082, high: 1.085, low: 1.078, close: 1.079 },
  { open: 1.079, high: 1.083, low: 1.077, close: 1.081 },
  { open: 1.081, high: 1.088, low: 1.08, close: 1.087 },
  { open: 1.087, high: 1.09, low: 1.084, close: 1.085 },
  { open: 1.085, high: 1.089, low: 1.083, close: 1.088 },
  { open: 1.088, high: 1.091, low: 1.086, close: 1.087 },
  { open: 1.087, high: 1.09, low: 1.084, close: 1.086 },
  { open: 1.086, high: 1.088, low: 1.082, close: 1.083 },
  { open: 1.083, high: 1.086, low: 1.081, close: 1.085 },
  { open: 1.085, high: 1.089, low: 1.083, close: 1.088 },
];

export const TRADE_DETAIL_TIMELINE_CHECK_ICON = uiAssets.timelineCheck;

export function getTradeDetailPageTitle(): string {
  return t('trade.detail.title');
}

export function getTradeDetailTimelineTitle(): string {
  return t('trade.detail.timeline');
}

export const SEED_TRADES: TradeRecord[] = [
  {
    id: 'T-2401',
    pair: 'EUR/USD',
    platform: 'global',
    strategy: 'Alpha Momentum',
    indicator: 'MACD',
    duration: '1m',
    direction: 'up',
    amount: 25,
    stakeLabel: '$25',
    result: '+$22.5',
    resultTone: 'success',
    status: 'profit',
    source: 'bot',
    timeLabel: '12:41',
    isToday: true,
    entryTime: '12:41:02',
    exitTime: '12:42:02',
    signalStrength: '82%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 34,
  },
  {
    id: 'T-2402',
    pair: 'USD/IDR OTC',
    platform: 'binolla',
    strategy: 'OTC Hunter',
    indicator: 'RSI',
    duration: '30s',
    direction: 'up',
    amount: 50,
    stakeLabel: '$50',
    result: '+$45',
    resultTone: 'success',
    status: 'profit',
    source: 'bot',
    timeLabel: '12:34',
    isToday: true,
    entryTime: '12:34:10',
    exitTime: '12:34:40',
    signalStrength: '78%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 41,
  },
  {
    id: 'T-2403',
    pair: 'BTC/USD',
    platform: 'global',
    strategy: 'Scar Precision',
    indicator: 'Bollinger',
    duration: '5m',
    direction: 'down',
    amount: 100,
    stakeLabel: '$100',
    result: '-$100',
    resultTone: 'danger',
    status: 'loss',
    source: 'bot',
    timeLabel: '12:22',
    isToday: true,
    entryTime: '12:22:15',
    exitTime: '12:27:15',
    signalStrength: '71%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 53,
  },
  {
    id: 'T-2415',
    pair: 'GBP/USD',
    platform: 'global',
    strategy: 'Alpha Momentum',
    indicator: 'MACD',
    duration: '3m',
    direction: 'up',
    amount: 25,
    stakeLabel: '$25',
    status: 'running',
    source: 'bot',
    timeLabel: '12:18',
    isToday: true,
    liveTimerSeconds: 24,
    entryTime: '12:41:02',
    exitTime: '12:42:02',
    signalStrength: '82%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 57,
  },
  {
    id: 'T-2404',
    pair: 'AUD/USD',
    platform: 'global',
    strategy: 'Trend Breaker',
    indicator: 'Stochastic',
    duration: '2m',
    direction: 'down',
    amount: 30,
    stakeLabel: '$30',
    result: '-$30',
    resultTone: 'danger',
    status: 'loss',
    source: 'user',
    timeLabel: '11:58',
    isToday: true,
    entryTime: '11:58:04',
    exitTime: '12:00:04',
    signalStrength: '65%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 77,
  },
  {
    id: 'T-2405',
    pair: 'EUR/JPY',
    platform: 'binolla',
    strategy: 'Red Signal Pro',
    indicator: 'Moving Average',
    duration: '1m',
    direction: 'up',
    amount: 20,
    stakeLabel: '$20',
    result: '+$18',
    resultTone: 'success',
    status: 'profit',
    source: 'bot',
    timeLabel: '11:42',
    isToday: true,
    entryTime: '11:42:18',
    exitTime: '11:43:18',
    signalStrength: '80%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 93,
  },
  {
    id: 'T-2398',
    pair: 'EUR/USD',
    platform: 'global',
    strategy: 'Alpha Momentum',
    indicator: 'MACD',
    duration: '1m',
    direction: 'up',
    amount: 25,
    stakeLabel: '$25',
    result: '+$20',
    resultTone: 'success',
    status: 'profit',
    source: 'user',
    timeLabel: '09:15',
    isToday: false,
    entryTime: '09:15:22',
    exitTime: '09:16:22',
    signalStrength: '76%',
    candleData: SHARED_CANDLE_DATA,
    openedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
];

export function getHistoryPageContent() {
  return {
    title: t('history.title'),
    filterAriaLabel: t('history.filterAria'),
    filterOptions: [
      { id: 'all' as const, label: t('history.filter.all') },
      { id: 'live' as const, label: t('history.filter.live') },
      { id: 'profit' as const, label: t('history.filter.profit') },
      { id: 'loss' as const, label: t('history.filter.loss') },
      { id: 'today' as const, label: t('history.filter.today') },
    ],
    emptyAllMessage: t('history.emptyAll'),
    emptyAllDescription: t('history.emptyAllDesc'),
    emptyFilterMessage: t('history.emptyFilter'),
    emptyFilterDescription: t('history.emptyFilterDesc'),
    detailsLabel: t('history.details'),
    viewChartLabel: t('history.viewChart'),
  };
}

export const DEFAULT_PAGE_SIZE = 20;
